################################
# Buildkite benchmarks pipeline
################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v3.0.1-oasis1:
    image: "oasislabs/testing:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.coveralls:/root/.coveralls
      - /var/lib/buildkite-agent/.buildkite:/root/.buildkite
      # Shared Rust target artifacts cache.
      - /var/tmp/cargo_target:/cargo_target
      # Shared Rust package checkouts directory.
      - /var/tmp/cargo_pkg/git:/root/.cargo/git
      - /var/tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /var/tmp/xargo_cache:/root/.xargo
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/workdir/target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "RUSTFLAGS=-C target-feature=+aes,+ssse3"
      - "GOPROXY=https://proxy.golang.org/"
    propagate-environment: true
    unconfined: true

steps:
  - label: Build artifacts
    branches: master
    command:
      - .buildkite/scripts/build_benchmarking_context.sh context.tar.gz
    artifact_paths:
      - context.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: ":rocket: Publish benchmarking docker image"
    trigger: private-ops-oasis-runtime-benchmarking-publish-image
    async: true
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        OASIS_RUNTIME_JOB_ID: "${BUILDKITE_JOB_ID}"
        OASIS_RUNTIME_COMMIT: "${BUILDKITE_COMMIT}"
        OASIS_RUNTIME_BRANCH: "${BUILDKITE_BRANCH}"
