##################################
# Daily buildkite docker pipeline
##################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v3.0.1-oasis1:
    image: "oasislabs/testing:0.2.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      - /var/lib/buildkite-agent/.coveralls:/root/.coveralls
      - /var/lib/buildkite-agent/.buildkite:/root/.buildkite
      # Shared Rust target artifacts cache.
      - /var/lib/buildkite-agent/.cache/cargo_target:/cargo_target
      # Shared Rust package checkouts directory.
      - /var/lib/buildkite-agent/.cache/cargo_pkg/git:/root/.cargo/git
      - /var/lib/buildkite-agent/.cache/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /var/lib/buildkite-agent/.cache/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /var/lib/buildkite-agent/.cache/go_pkg:/root/go/pkg
    tmpfs:
      - /tmp:exec
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/cargo_target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
    propagate-environment: true
    unconfined: true

steps:
  - label: Build runtime benchmark
    command:
      - .buildkite/scripts/build_tag_push_benchmark_image.sh
    agents:
      buildkite_agent_size: large

  - label: Celer tests
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/scripts/run_dapp_test.sh celer
    timeout_in_minutes: 25
    # use default: exit-status: "*" and retry limit of 2
    retry:
      automatic: true
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Augur tests
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - .buildkite/scripts/run_dapp_test.sh augur
    timeout_in_minutes: 20
    # use default: exit-status: "*" and retry limit of 2
    retry:
      automatic: true
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: "Trigger benchmark run"
    trigger: private-ops-run-benchmarks
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master
