##################################
# Docker image deployment pipeline
##################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v2.1.0-oasis4:
    image: "oasislabs/development:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      # Shared Rust incremental compile caches.
      - /tmp/cargo_ic/release:/workdir/target/release/incremental
      - /tmp/cargo_ic/release_sgx:/workdir/target/x86_64-fortanix-unknown-sgx/release/incremental
      # Shared Rust package checkouts directory.
      - /tmp/cargo_pkg/git:/root/.cargo/git
      - /tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /tmp/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /tmp/go_pkg:/root/go/pkg
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/workdir/target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "RUSTFLAGS=-C target-feature=+aes,+ssse3"
    propagate-environment: true

steps:
  - label: Extract platform resources (master branches only)
    branches: master
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform
    artifact_paths:
      - platform/*

  - label: Extract platform resources (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform
    artifact_paths:
      - platform/*
    env:
      BASE_VARIANT: beta

  - label: Extract production-track platform resources (master branches only)
    branches: master
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform-prod
    artifact_paths:
      - platform-prod/*

  - label: Extract production-track platform resources (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform-prod latest-beta
    artifact_paths:
      - platform-prod/*

  - wait

  - label: Get docker tag and save it as metadata for use later
    command: .buildkite/scripts/set_docker_tag_meta_data.sh

  - label: Build artifacts
    branches: master beta
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - eval $(ssh-agent -s)
      - ssh-add
      - .buildkite/scripts/build_deployment_context.sh platform context.tar.gz
    artifact_paths:
      - context.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build benchmarking artifacts
    branches: master beta
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - eval $(ssh-agent -s)
      - ssh-add
      - .buildkite/scripts/build_deployment_context.sh platform context-bench.tar.gz
    env:
      BUILD_BENCHMARKING: "1"
    artifact_paths:
      - context-bench.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build production-track artifacts
    branches: master beta
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - eval $(ssh-agent -s)
      - ssh-add
      - .buildkite/scripts/build_deployment_context.sh platform-prod context-prod.tar.gz
    env:
      BUILD_PRODUCTION_GENESIS: "1"
    artifact_paths:
      - context-prod.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: Update testing docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh latest-testing
    env:
      BASE_VARIANT: testing
      DEPLOYMENT_VARIANT: testing

  - label: Update testing docker image tags (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh latest-testing-beta
    env:
      BASE_VARIANT: testing
      DEPLOYMENT_VARIANT: testing

  - label: Update benchmarking docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context-bench.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh latest-benchmarking
    env:
      BASE_VARIANT: testing
      DEPLOYMENT_VARIANT: benchmarking

  - label: Update benchmarking docker image tags (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context-bench.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh latest-benchmarking-beta
    env:
      BASE_VARIANT: testing
      DEPLOYMENT_VARIANT: benchmarking

  - label: Update staging docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context-prod.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging

  - label: Update staging beta docker image tags (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context-prod.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging-beta
    env:
      BASE_VARIANT: beta
      DEPLOYMENT_VARIANT: beta

  - wait

  - label: "Trigger staging deployment (master branches only)"
    trigger: private-ops-deploy-ekiden-staging
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Trigger staging beta deployment (beta branch only)"
    trigger: private-ops-deploy-ekiden-staging-beta
    branches: beta
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Trigger hardware staging deployment (master branches only)"
    trigger: private-ops-deploy-ekiden-hardware-staging
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Build and push all-in-one image (master branches only)"
    branches: master
    command:
      - ./docker/all-in-one/build.sh
      - docker tag local-aio:latest oasislabs/private-all-in-one:latest
      - docker push oasislabs/private-all-in-one:latest

  - label: "Build and push all-in-one image (beta branch only)"
    branches: beta
    command:
      - ./docker/all-in-one/build.sh
      - docker tag local-aio:latest oasislabs/private-all-in-one:latest-beta
      - docker push oasislabs/private-all-in-one:latest-beta
