##
# Docker image deployment pipeline
#
# This is a scheduled pipeline for automatic production deployments.
##
common_tools_plugin: &common_tools_plugin
  oasislabs/private-oasis-buildkite-tools#v0.2.0: ~

steps:
  - label: Update production docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/promote_docker_image_to.sh --from-image-tag staging oasislabs/ekiden-runtime-ethereum next-production-deployment
    plugins:
      - *common_tools_plugin
