##################################
# Docker image deployment pipeline
##################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v2.1.0-oasis4:
    image: "oasisprotocol/oasis-core-ci:stable-20.8.x"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      # Shared Rust incremental compile caches.
      - /var/tmp/cargo_ic/release:/workdir/target/release/incremental
      - /var/tmp/cargo_ic/release_sgx:/workdir/target/x86_64-fortanix-unknown-sgx/release/incremental
      # Shared Rust package checkouts directory.
      - /var/tmp/cargo_pkg/git:/root/.cargo/git
      - /var/tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /var/tmp/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /var/tmp/go_pkg:/root/go/pkg
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/workdir/target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "RUSTFLAGS=-C target-feature=+aes,+ssse3"
    propagate-environment: true

steps:
  - label: Get docker tag and save it as metadata for use later
    branches: master ptrus/feature/oasis-core-20-9
    command: .buildkite/scripts/set_docker_tag_meta_data.sh

  - label: Build testing artifacts
    branches: master ptrus/feature/oasis-core-20-9
    command:
      - .buildkite/scripts/build_deployment_context.sh context.tar.gz
    artifact_paths:
      - context.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build benchmarking artifacts
    branches: master ptrus/feature/oasis-core-20-9
    command:
      - .buildkite/scripts/build_deployment_context.sh context-bench.tar.gz
    env:
      BUILD_BENCHMARKING: "1"
    artifact_paths:
      - context-bench.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build production-track artifacts
    branches: master ptrus/feature/oasis-core-20-9
    command:
      - .buildkite/scripts/build_deployment_context.sh context-prod.tar.gz
    env:
      BUILD_PRODUCTION_GENESIS: "1"
    artifact_paths:
      - context-prod.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: ":rocket: Publish docker images"
    trigger: private-ops-oasis-runtime-publish-image
    async: true
    branches: master ptrus/feature/oasis-core-20-9
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        OASIS_RUNTIME_JOB_ID: "${BUILDKITE_JOB_ID}"
        OASIS_RUNTIME_COMMIT: "${BUILDKITE_COMMIT}"
        OASIS_RUNTIME_BRANCH: "${BUILDKITE_BRANCH}"
