##################################
# Docker image deployment pipeline
##################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v3.0.1-oasis1:
    image: "oasislabs/development:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      - /var/lib/buildkite-agent/.ssh:/root/.ssh
      # Shared Rust incremental compile caches.
      - /var/lib/buildkite-agent/.cache/cargo_ic/release:/workdir/target/release/incremental
      - /var/lib/buildkite-agent/.cache/cargo_ic/release_sgx:/workdir/target/x86_64-fortanix-unknown-sgx/release/incremental
      # Shared Rust package checkouts directory.
      - /var/lib/buildkite-agent/.cache/cargo_pkg/git:/root/.cargo/git
      - /var/lib/buildkite-agent/.cache/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /var/lib/buildkite-agent/.cache/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /var/lib/buildkite-agent/.cache/go_pkg:/root/go/pkg
    tmpfs:
      - /tmp:exec
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/workdir/target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "RUSTFLAGS=-C target-feature=+aes,+ssse3"
    propagate-environment: true

steps:
  - label: Extract platform resources
    branches: master beta
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform
    artifact_paths:
      - platform/*

  - wait

  - label: Get docker tag and save it as metadata for use later
    command: .buildkite/scripts/set_docker_tag_meta_data.sh

  - label: Build artifacts (master branches only)
    branches: master beta
    command:
      - .buildkite/scripts/setup_gitconfig.sh
      - eval $(ssh-agent -s)
      - ssh-add
      - .buildkite/scripts/build_deployment_context.sh platform context.tar.gz
    artifact_paths:
      - context.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: Update staging docker image tags (master branches only)
    branches: master
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging

  - label: Update staging beta docker image tags (beta branch only)
    branches: beta
    command:
      - .buildkite/scripts/build_tag_push_deployment_image.sh context.tar.gz
      - .buildkite/scripts/promote_deployment_image_to.sh staging-beta

  - wait

  - label: "Trigger staging deployment (master branches only)"
    trigger: private-ops-deploy-ekiden-staging
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Trigger staging beta deployment (beta branch only)"
    trigger: private-ops-deploy-ekiden-staging-beta
    branches: beta
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master

  - label: "Trigger hardware staging deployment (master branches only)"
    trigger: private-ops-deploy-ekiden-hardware-staging
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: master
