##################################
# Docker image deployment pipeline
##################################
docker_plugin: &docker_plugin_configuration
  oasislabs/docker#v2.1.0-oasis4:
    image: "oasislabs/development:0.3.0"
    always_pull: true
    workdir: /workdir
    volumes:
      - .:/workdir
      # Shared Rust incremental compile caches.
      - /tmp/cargo_ic/release:/workdir/target/release/incremental
      - /tmp/cargo_ic/release_sgx:/workdir/target/x86_64-fortanix-unknown-sgx/release/incremental
      # Shared Rust package checkouts directory.
      - /tmp/cargo_pkg/git:/root/.cargo/git
      - /tmp/cargo_pkg/registry:/root/.cargo/registry
      # Shared Rust SGX standard library artifacts cache.
      - /tmp/xargo_cache:/root/.xargo
      # Shared Go package checkouts directory.
      - /tmp/go_pkg:/root/go/pkg
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "CARGO_TARGET_DIR=/workdir/target"
      - "CARGO_INSTALL_ROOT=/root/.cargo"
      - "RUSTFLAGS=-C target-feature=+aes,+ssse3"
    propagate-environment: true

steps:
  - label: Extract platform resources
    branches: master
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform
    artifact_paths:
      - platform/*

  - label: Extract platform resources
    branches: devnet2.1
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform
    artifact_paths:
      - platform/*
    env:
      BASE_VARIANT: devnet2.1

  - label: Extract production-track platform resources
    branches: master
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform-prod
    artifact_paths:
      - platform-prod/*

  - label: Extract production-track platform resources
    branches: devnet2.1
    command:
      - .buildkite/scripts/extract_platform_resources.sh platform-prod latest-devnet2.1
    artifact_paths:
      - platform-prod/*

  - wait

  - label: Get docker tag and save it as metadata for use later
    branches: master
    command: .buildkite/scripts/set_docker_tag_meta_data.sh

  - label: Build testing artifacts
    branches: master devnet2.1
    command:
      - .buildkite/scripts/build_deployment_context.sh platform context.tar.gz
    artifact_paths:
      - context.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build benchmarking artifacts
    branches: master devnet2.1
    command:
      - .buildkite/scripts/build_deployment_context.sh platform context-bench.tar.gz
    env:
      BUILD_BENCHMARKING: "1"
    artifact_paths:
      - context-bench.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - label: Build production-track artifacts
    branches: master devnet2.1
    command:
      - .buildkite/scripts/build_deployment_context.sh platform-prod context-prod.tar.gz
    env:
      BUILD_PRODUCTION_GENESIS: "1"
    artifact_paths:
      - context-prod.tar.gz
    agents:
      buildkite_agent_size: large
    plugins:
      <<: *docker_plugin_configuration

  - wait

  - label: ":rocket: Publish docker images"
    trigger: private-ops-oasis-runtime-publish-image
    async: true
    branches: master
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        OASIS_RUNTIME_JOB_ID: "${BUILDKITE_JOB_ID}"
        OASIS_RUNTIME_COMMIT: "${BUILDKITE_COMMIT}"
        OASIS_RUNTIME_BRANCH: "${BUILDKITE_BRANCH}"

  - label: ":rocket: Publish docker images"
    trigger: private-ops-oasis-runtime-publish-image
    async: true
    branches: devnet2.1
    build:
      message: "${BUILDKITE_MESSAGE}"
      env:
        OASIS_RUNTIME_JOB_ID: "${BUILDKITE_JOB_ID}"
        OASIS_RUNTIME_COMMIT: "${BUILDKITE_COMMIT}"
        OASIS_RUNTIME_BRANCH: "${BUILDKITE_BRANCH}"
        IMAGE_VARIANT: devnet2.1
